# Generated by Django 2.2.2 on 2019-11-16 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_ws84', django.contrib.gis.db.models.fields.PointField(srid=4327)),
                ('punto', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('multi_punto', django.contrib.gis.db.models.fields.MultiPointField(srid=32718)),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(srid=32718)),
                ('multi_poli', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32718)),
                ('linea', django.contrib.gis.db.models.fields.LineStringField(srid=32718)),
                ('multi_linea', django.contrib.gis.db.models.fields.MultiLineStringField(srid=32718)),
            ],
        ),
    ]
