# Generated by Django 2.2.2 on 2019-11-16 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdedatos',
            name='punto_ws84',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
