# Generated by Django 2.2.2 on 2020-02-28 16:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdedatos',
            name='linea',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=32718),
        ),
        migrations.AlterField(
            model_name='tiposdedatos',
            name='multi_linea',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=32718),
        ),
        migrations.AlterField(
            model_name='tiposdedatos',
            name='multi_poli',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32718),
        ),
        migrations.AlterField(
            model_name='tiposdedatos',
            name='multi_punto',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=32718),
        ),
        migrations.AlterField(
            model_name='tiposdedatos',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=32718),
        ),
        migrations.AlterField(
            model_name='tiposdedatos',
            name='punto',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32718),
        ),
        migrations.AlterField(
            model_name='tiposdedatos',
            name='punto_ws84',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
